font:
  size: 18
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0
env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 120
    lines: 30
  position:
    x: 1100
    y: 400
  decorations: buttonless
  # dynamic_padding: true
  padding:
    x: 10
    y: 10

selection:
  save_to_clipboard: true

mouse:
  hide_when_typing: true

# colors:
#   primary:
#     background: '#2e3440'
#     foreground: '#d8dee9'
#     dim_foreground: '#a5abb6'
#   cursor:
#     text: '#2e3440'
#     cursor: '#d8dee9'
#   vi_mode_cursor:
#     text: '#2e3440'
#     cursor: '#d8dee9'
#   selection:
#     text: CellForeground
#     background: '#4c566a'
#   search:
#     matches:
#       foreground: CellBackground
#       background: '#88c0d0'
#     bar:
#       background: '#434c5e'
#       foreground: '#d8dee9'
#   normal:
#     black: '#3b4252'
#     red: '#bf616a'
#     green: '#a3be8c'
#     yellow: '#ebcb8b'
#     blue: '#81a1c1'
#     magenta: '#b48ead'
#     cyan: '#88c0d0'
#     white: '#e5e9f0'
#   bright:
#     black: '#4c566a'
#     red: '#bf616a'
#     green: '#a3be8c'
#     yellow: '#ebcb8b'
#     blue: '#81a1c1'
#     magenta: '#b48ead'
#     cyan: '#8fbcbb'
#     white: '#eceff4'
#   dim:
#     black: '#373e4d'
#     red: '#94545d'
#     green: '#809575'
#     yellow: '#b29e75'
#     blue: '#68809a'
#     magenta: '#8c738c'
#     cyan: '#6d96a5'
#     white: '#aeb3bb'

key_bindings:
  - { key: Y, mods: Control, action: ToggleViMode }
