#!/bin/bash

GetModificationFootprint() {
  case `uname -s` in
    "Linux")
      find $1 -type f -print0 -exec date -r '{}' \;
      ;;
    "Darwin")
      find $1 -type f -print0 -exec stat -f "%m" '{}' \;
  esac
}

while true
do
  ATIME=`GetModificationFootprint "$1"`

  if [[ "$ATIME" != "$LTIME" ]]
  then
    clear;
    $2 $3 $4 $5 $6 $7 $8 $9
    LTIME=$ATIME
  fi

  sleep 0.2
done
